### ISSUE TITLE
Question about get_elev_point()

### ISSUE THREAD

**Issue by xiaobrnbrn** [USEPA/elevatr#72]
Thanks a lot for your excellent work! I have tested a data from HongKong using get_elev_point(). However, this function return **NA** if the param **src** is set as **"epqs"**, as shown in the following picture. Let **src = "aws"** and it will return a specific elevation value.  I was confused for it.  Could you please explain the reason? Moreover, have you studied the accuracy of the obtained elevations? I would like to utilize them for robot localization (the errors within several meters are acceptable) and it may not work if they are just  rough references.

![Screenshot from 2022-06-07 12-08-47](https://user-images.githubusercontent.com/30363654/172294830-8236604a-2aec-461f-b765-553370e452ac.png)

**Comment by jhollist** [comment]
@xiaobrnbrn Glad you are finding elevatr useful!  Answers to your questions below.

First, the "epqs" source is a US only dataset.  That is why it is returning NA for areas around Hong Kong.  The "aws" source will be your only option for point elevations outside of the US.

Second,  I have not done any independent evaluation of error from the different sources.  That being said, there are several potential sources of error here.  First is the inherent error in the elevation data itself.  Second, is the the horizontal error introduced by the raster resolution (i.e. elevation will be a single averaged elevation for the land represented by a pixel).  Third will be temporal error since these data sources were all collected in the past, there is the potential for changes to elevation that occur over time).  

The error will depend on the zoom level (if using "aws") and the reported error from the source data.  For the data from OpenTopography you would need to dig into the details on each individual source.  Good place to start for that is https://portal.opentopography.org/dataCatalog?group=global.  The sources change based on zoom level for AWS and region.  All you need to know about zoom level, resolution and source data is at https://github.com/tilezen/joerd/blob/master/docs/data-sources.md.  

Not knowing the details of your project, it is hard to say if the data provided via elevatr will work or not.  I would not use elevatr data to support any real-time navigation.  It will be too coarse for that.  It is pretty good in many cases, but does have its limits.  Best use cases are mapping, hydrology, etc.

Hope this helps.

**Comment by xiaobrnbrn** [comment]
Thank you very much for your answer.
